version: '2'
services:
  fi1:
    image: container
    env_file: ./container1.env
    environment:
    - FI_DOMAIN=${FI1_DOMAIN}
    - OTHER_FI_DOMAIN=${FI2_DOMAIN}
    - BRIDGE_VERSION=${FI1_BRIDGE_VERSION}
    - OTHER_FI_BRIDGE_VERSION=${FI2_BRIDGE_VERSION}
    - RECEIVING_SEED=SBHH2T62R3ZJ25T2MIQL7EQVIAWAPTNQH5MAQTWS3S34LY7LR246AKKR
    - SIGNING_SEED=SDPAANPYVG3UZ2MZH36YPM53OZSF6P4RN7UWXTKEP5KAOEWCOWZFLSSU
    - COMPLIANCE_EXTERNAL_PORT=8002
    ports:
    - "8000:8003"
    networks:
    - fi1
  fi2:
    image: container
    env_file: ./container2.env
    environment:
    - FI_DOMAIN=${FI2_DOMAIN}
    - OTHER_FI_DOMAIN=${FI1_DOMAIN}
    - BRIDGE_VERSION=${FI2_BRIDGE_VERSION}
    - OTHER_FI_BRIDGE_VERSION=${FI1_BRIDGE_VERSION}
    - RECEIVING_SEED=SD3NMCYX4KUEGZH2PC3V57WI2EPDMBXKDSLBYCSDSCJ6KCKXGOHLWHES
    - SIGNING_SEED=SBIHF5V7XFLT6MMXZAIDEAMWPIRE5HZ5DY6EJ2DQ345AHWU3UU5K35LX
    - COMPLIANCE_EXTERNAL_PORT=8002
    ports:
    - "9000:8003"
    networks:
    - fi2
  postgres1:
    image: "postgres:9.6.1"
    networks:
      fi1:
        aliases:
          - db
  postgres2:
    image: "postgres:9.6.1"
    networks:
      fi2:
        aliases:
          - db
networks:
  fi1:
  fi2:
